name: Test

main: Crow\Test\Main

version: 1.0.0

api: [3.0.0,4.0.0]

load: POSTWORLD

author: Crow

description: "ein wünsche erfüllen plugin"

commands:

  Kanal:

    description: §4Unser YT-Channel

    usage: "/Kanal"

    permission: YT.command

